const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const core=require('../storage-core'),{createBackupStore}=require('../backup-store');
function memory(seed={}) { const map=new Map(Object.entries(seed));let fail=false;return {get length(){return map.size;},key:i=>Array.from(map.keys())[i],getItem:k=>map.get(k)??null,setItem(k,v){if(fail)throw Error('quota');map.set(k,v);},removeItem:k=>map.delete(k),fail:v=>fail=v}; }
const snapshot=entries=>({format:'3566-notebook-backup',version:1,createdAt:new Date().toISOString(),entries});
test('日期校验兼容旧格式，拒绝错误日期',()=>{for(const k of ['w-2026-9-3','w-2026-09-03','p-2024-2-29'])assert(core.knownKey(k));for(const k of ['w-2026-2-30','w-2026-13-1','p-2026-2-29'])assert(!core.knownKey(k));});
test('已移除模块和秘密字段不会导出，也不能导入',()=>{const m=memory({'learn-compose-draft':'"笔记"','lol-review-history':'{}','game-review-log':'[]','k3-key':'"secret"','art-imgs-v3':'{}'}),store=core.create(m),out=store.snapshot(true,true);assert.deepEqual(Object.keys(out.entries),['learn-compose-draft']);for(const k of ['lol-review-history','game-review-log','riot-key','k3-key'])assert.throws(()=>core.validateSnapshot(snapshot({[k]:{}})));});
test('公开偏好、文学版本和新手状态可备份',()=>{core.validateSnapshot(snapshot({'ui-prefs':{onboardingVersion:1,style:'irises',museumPure:true},'w-2026-9-14':{done:{0:true},extra:[],hiddenBase:[],literaryDraft:'原稿',literaryVersions:[{draft:'原稿'}]},'reward-view':'reading'}));assert.throws(()=>core.validateEntry('reward-view','game'));});
test('写入失败保留未保存内容，重试成功',()=>{let notice='';const m=memory(),store=core.create(m,{notify:s=>notice=s});m.fail(true);assert.equal(store.write('learn-compose-draft','长文'),false);assert(notice);assert.equal(store.snapshot(true,true).entries['learn-compose-draft'],'长文');m.fail(false);assert(store.retry());assert.equal(store.read('learn-compose-draft',''),'长文');});
test('损坏记录原始证据不被覆盖',()=>{const m=memory({'learn-log':'{broken'}),s=core.create(m);s.read('learn-log',[]);assert.equal(s.write('learn-log',[]),false);assert.equal(m.getItem('learn-log'),'{broken');assert.equal(s.snapshot(false,true).recoveryRawEntries['learn-log'],'{broken');});
test('补缺恢复先备份，保留同名并冻结旧状态',async()=>{const m=memory({'learn-compose-draft':'"本机"'}),s=core.create(m);let before;await s.restore(snapshot({'learn-compose-draft':'文件','ui-prefs':{onboardingVersion:1}}),'missing',async x=>before=x);assert.equal(before.entries['learn-compose-draft'],'本机');assert.equal(s.read('learn-compose-draft',''),'本机');assert(s.status().frozen);});
test('未知字段和原型污染被拒绝',()=>{assert.throws(()=>core.validateSnapshot(snapshot({'notebook-prefs':JSON.parse('{"__proto__":{"polluted":true}}')})));assert.throws(()=>core.validateSnapshot({...snapshot({}),unexpected:true}));});
test('独立备份限制路径与保留规则',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'3566-public-store-')),s=createBackupStore(dir);for(let i=0;i<15;i++)s.write({kind:'auto',snapshot:snapshot({'learn-compose-draft':'记录'+i})});assert(s.list().length<=12);assert.throws(()=>s.read('../escape'));assert(s.read(s.list()[0].id).entries['learn-compose-draft']);});
